In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/owid.csv')
df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1850,AFG,3752993.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1851,AFG,3767956.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.157,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,Afghanistan,1852,AFG,3783940.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.156,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,Afghanistan,1853,AFG,3800954.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.156,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,Afghanistan,1854,AFG,3818038.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.155,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [4]:
cols = [
    'gdp',
    'nitrous_oxide_per_capita',
    'methane_per_capita',
    'gas_co2_per_capita',
    'total_ghg',
    'country',
    'co2_per_capita',
    'year',
    'iso_code',
    'population',
    'gdp',
    'temperature_change_from_ch4',
    'temperature_change_from_ghg',
    'temperature_change_from_co2',
    'temperature_change_from_n2o',
    'land_use_change_co2_per_capita',
    'co2',
    'methane',
    'nitrous_oxide',
    'total_ghg'
]

trunc_df = df[cols]

In [5]:
df_ghg = pd.read_csv('data/owid_ghg.csv')

df_ghg.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023'],
      dtype='object')

In [6]:
df_ghg_melted = pd.melt(df_ghg, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code' ], var_name="year", value_name='emissions')

df_ghg_melted_dropped_na = df_ghg_melted.dropna(subset=['emissions'])
df_ghg_melted_dropped_na.head()
df_ghg_melted_dropped_na['year'] = df_ghg_melted_dropped_na['year'].astype(int)
df_ghg_melted_dropped_na['Country Code'] = df_ghg_melted_dropped_na['Country Code'].astype(str)

C:\Users\iamam\AppData\Local\Temp\ipykernel_30780\2986736804.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ghg_melted_dropped_na['year'] = df_ghg_melted_dropped_na['year'].astype(int)
C:\Users\iamam\AppData\Local\Temp\ipykernel_30780\2986736804.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ghg_melted_dropped_na['Country Code'] = df_ghg_melted_dropped_na['Country Code'].astype(str)

In [7]:
merged_df = pd.merge(trunc_df, df_ghg_melted_dropped_na, left_on=['iso_code', 'year'], right_on=['Country Code', 'year'])

In [8]:
merged_df.head()

merged_df.rename(columns={"emissions": "HFC_PFC_others"})

,gdp,nitrous_oxide_per_capita,methane_per_capita,gas_co2_per_capita,total_ghg,country,co2_per_capita,year,iso_code,population,...,land_use_change_co2_per_capita,co2,methane,nitrous_oxide,total_ghg,Country Name,Country Code,Indicator Name,Indicator Code,HFC_PFC_others
0,1.581223e+10,NaN,NaN,0.020,NaN,Afghanistan,0.155,1970,AFG,10752973.0,...,0.638,1.670,NaN,NaN,NaN,Afghanistan,AFG,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,-679.915897
1,1.577051e+10,NaN,NaN,0.040,NaN,Afghanistan,0.172,1971,AFG,11015853.0,...,0.539,1.894,NaN,NaN,NaN,Afghanistan,AFG,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,-584.266024
2,1.317055e+10,NaN,NaN,0.027,NaN,Afghanistan,0.136,1972,AFG,11286753.0,...,0.481,1.530,NaN,NaN,NaN,Afghanistan,AFG,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,-365.030981
3,1.356863e+10,NaN,NaN,0.029,NaN,Afghanistan,0.141,1973,AFG,11575308.0,...,0.394,1.635,NaN,NaN,NaN,Afghanistan,AFG,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,-295.756284
4,1.430911e+10,NaN,NaN,0.034,NaN,Afghanistan,0.161,1974,AFG,11869881.0,...,0.347,1.913,NaN,NaN,NaN,Afghanistan,AFG,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,-67.278590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8597,2.281143e+10,0.448,0.949,0.000,42.23,Zimbabwe,0.848,2012,ZWE,13265331.0,...,1.080,11.254,12.59,5.94,42.23,Zimbabwe,ZWE,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,1827.732117
8598,2.326196e+10,0.421,0.918,0.000,42.19,Zimbabwe,0.861,2013,ZWE,13555420.0,...,0.969,11.671,12.45,5.71,42.19,Zimbabwe,ZWE,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,1972.408020
8599,2.381884e+10,0.362,0.826,0.000,40.34,Zimbabwe,0.862,2014,ZWE,13855758.0,...,0.835,11.946,11.45,5.02,40.34,Zimbabwe,ZWE,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,1933.483643
8600,2.424616e+10,0.392,0.876,0.000,41.86,Zimbabwe,0.866,2015,ZWE,14154937.0,...,0.762,12.255,12.40,5.55,41.86,Zimbabwe,ZWE,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,2499.469604
8601,2.436205e+10,0.351,0.828,0.000,115.32,Zimbabwe,0.729,2016,ZWE,14452705.0,...,0.711,10.533,11.97,5.08,115.32,Zimbabwe,ZWE,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE,1587.372070

In [9]:
merged_df.to_csv('data/emissions_merged_no2_ch4_.csv', index=False)